version: '3.8'

services:
  nginx:
    build:
      context: './nginx'
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "8085:8085"  # HTTP
      - "8443:443"   # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount the Nginx configuration file
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
      - grafana
      - prometheus
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - CERT_CN=localhost
      - COMPOSE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"  # Expose backend API directly for dev/testing
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=project_management
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM=noreply@projectmanagement.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      - postgres
      - mailhog
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["sh", "./scripts/docker-entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Expose frontend dev server directly for dev/testing
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000" 
    volumes:
      - ./grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://localhost:8443/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true  # Enable subpath support
    depends_on:
      - prometheus
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"  # Postgres database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # MailHog UI
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"  # Adminer UI
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - app-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - app-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    networks:
      - app-network
    environment:
      - REDIS_ADDR=redis:6379

volumes:
  postgres_data:
  grafana-storage:
  redis_data:

networks:
  app-network:
    driver: bridge