global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          environment: 'development'
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'development'
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']
        labels:
          environment: 'development'
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          environment: 'development'