import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateExistingTables1743965638042 implements MigrationInterface {
    name = 'UpdateExistingTables1743965638042'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "fk_fc4eda9260de95137bcd5b0671c"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "fk_4d4ad0f71d22e3b7fc6ed325a1d"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "fk_6928b8bc3071ae9b571f9fca34d"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP CONSTRAINT "fk_8f2891c6b29117202c4107d4c30"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP CONSTRAINT "fk_903ca5e01a0a42c91b2d290658d"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP CONSTRAINT "fk_7ac7193684dde3bc222ca652957"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP CONSTRAINT "fk_65eb082544fd64cff2e17ec1760"`);
        await queryRunner.query(`ALTER TABLE "suppliers" RENAME COLUMN "contactperson" TO "contactPerson"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "projectid"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "purchasedate"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "costperunit"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "totalvalue"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "lowstockthreshold"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "locationid"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "supplierid"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "serialnumber"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "imageurl"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "unitofmeasure"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultusefullifemin"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultusefullifemax"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultsalvagevaluepercent"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "isactive"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "createdat"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "updatedat"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultdepreciationmethod"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "categoryid"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "acquisitiondate"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "originalcost"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "usefullife"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "salvagevalue"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "currentvalue"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "accumulateddepreciation"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "lastdepreciationdate"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "disposaldate"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "disposalproceeds"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "createdat"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "updatedat"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "serialnumber"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "depreciationmethod"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "disposalreason"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "assettag"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "assetid"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "disposaldate"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "disposalproceeds"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "disposalcosts"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "netbookvalue"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "gainloss"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "createdat"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "assetid"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "bookvaluebefore"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "bookvalueafter"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "postingdate"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "createdat"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "assetid"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "revaluationdate"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "previousvalue"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "newvalue"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "createdat"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "createdby"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "userid"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "entitytype"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "entityid"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "entityname"`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "clientName" character varying`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "budget" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "projects" ADD "spent" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastLogin" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phoneNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "jobTitle" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "profilePictureUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "permissions" text`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "unitOfMeasure" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "projectId" uuid`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "purchaseDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "costPerUnit" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "totalValue" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "lowStockThreshold" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "serialNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "locationId" integer`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "supplierId" integer`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultUsefulLifeMin" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultUsefulLifeMax" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultDepreciationMethod" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultSalvageValuePercent" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "assetTag" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "categoryId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "acquisitionDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "originalCost" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "usefulLife" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "depreciationMethod" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "salvageValue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "currentValue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "accumulatedDepreciation" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "serialNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "lastDepreciationDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "disposalDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "disposalProceeds" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "disposalReason" character varying`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "assetId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "disposalDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "disposalProceeds" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "disposalCosts" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "netBookValue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "gainLoss" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "assetId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "bookValueBefore" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "bookValueAfter" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "postingDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "assetId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "revaluationDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "previousValue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "newValue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "createdBy" integer`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "userName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "entityType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "entityId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "entityName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "timestamp" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_fc4eda9260de95137bcd5b0671c" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_4d4ad0f71d22e3b7fc6ed325a1d" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_6928b8bc3071ae9b571f9fca34d" FOREIGN KEY ("supplierId") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD CONSTRAINT "FK_8f2891c6b29117202c4107d4c30" FOREIGN KEY ("categoryId") REFERENCES "asset_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD CONSTRAINT "FK_903ca5e01a0a42c91b2d290658d" FOREIGN KEY ("assetId") REFERENCES "fixed_assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD CONSTRAINT "FK_7ac7193684dde3bc222ca652957" FOREIGN KEY ("assetId") REFERENCES "fixed_assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD CONSTRAINT "FK_65eb082544fd64cff2e17ec1760" FOREIGN KEY ("assetId") REFERENCES "fixed_assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP CONSTRAINT "FK_65eb082544fd64cff2e17ec1760"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP CONSTRAINT "FK_7ac7193684dde3bc222ca652957"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP CONSTRAINT "FK_903ca5e01a0a42c91b2d290658d"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP CONSTRAINT "FK_8f2891c6b29117202c4107d4c30"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_6928b8bc3071ae9b571f9fca34d"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_4d4ad0f71d22e3b7fc6ed325a1d"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_fc4eda9260de95137bcd5b0671c"`);
        await queryRunner.query(`ALTER TABLE "activities" ALTER COLUMN "timestamp" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "entityName"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "entityId"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "entityType"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "userName"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "newValue"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "previousValue"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "revaluationDate"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" DROP COLUMN "assetId"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "postingDate"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "bookValueAfter"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "bookValueBefore"`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" DROP COLUMN "assetId"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "gainLoss"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "netBookValue"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "disposalCosts"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "disposalProceeds"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "disposalDate"`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" DROP COLUMN "assetId"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "disposalReason"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "disposalProceeds"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "disposalDate"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "lastDepreciationDate"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "serialNumber"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "accumulatedDepreciation"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "currentValue"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "salvageValue"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "depreciationMethod"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "usefulLife"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "originalCost"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "acquisitionDate"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" DROP COLUMN "assetTag"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultSalvageValuePercent"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultDepreciationMethod"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultUsefulLifeMax"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "defaultUsefulLifeMin"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "supplierId"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "locationId"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "serialNumber"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "lowStockThreshold"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "totalValue"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "costPerUnit"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "purchaseDate"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "projectId"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "unitOfMeasure"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "profilePictureUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "jobTitle"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastLogin"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "spent"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "budget"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "clientName"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "entityname" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "entityid" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "entitytype" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "activities" ADD "userid" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "createdby" integer`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "createdat" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "newvalue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "previousvalue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "revaluationdate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD "assetid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "createdby" integer`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "createdat" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "postingdate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "bookvalueafter" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "bookvaluebefore" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD "assetid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "createdby" integer`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "createdat" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "gainloss" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "netbookvalue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "disposalcosts" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "disposalproceeds" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "disposaldate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD "assetid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "assettag" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "disposalreason" character varying`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "depreciationmethod" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "serialnumber" character varying`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "createdby" integer`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "updatedat" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "createdat" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "disposalproceeds" numeric(12,2)`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "disposaldate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "lastdepreciationdate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "accumulateddepreciation" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "currentvalue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "salvagevalue" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "usefullife" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "originalcost" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "acquisitiondate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD "categoryid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultdepreciationmethod" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "createdby" integer`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "updatedat" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "createdat" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "isactive" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultsalvagevaluepercent" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultusefullifemax" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "defaultusefullifemin" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "unitofmeasure" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "imageurl" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "serialnumber" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "supplierid" integer`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "locationid" integer`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "lowstockthreshold" integer DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "totalvalue" numeric(12,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "costperunit" numeric(12,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "purchasedate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "projectid" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" RENAME COLUMN "contactPerson" TO "contactperson"`);
        await queryRunner.query(`ALTER TABLE "asset_revaluations" ADD CONSTRAINT "fk_65eb082544fd64cff2e17ec1760" FOREIGN KEY ("assetid") REFERENCES "fixed_assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "depreciation_entries" ADD CONSTRAINT "fk_7ac7193684dde3bc222ca652957" FOREIGN KEY ("assetid") REFERENCES "fixed_assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disposal_entries" ADD CONSTRAINT "fk_903ca5e01a0a42c91b2d290658d" FOREIGN KEY ("assetid") REFERENCES "fixed_assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fixed_assets" ADD CONSTRAINT "fk_8f2891c6b29117202c4107d4c30" FOREIGN KEY ("categoryid") REFERENCES "asset_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "fk_6928b8bc3071ae9b571f9fca34d" FOREIGN KEY ("supplierid") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "fk_4d4ad0f71d22e3b7fc6ed325a1d" FOREIGN KEY ("projectid") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "fk_fc4eda9260de95137bcd5b0671c" FOREIGN KEY ("locationid") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
